import Gantt

events = [
    #First 6 seconds b4 p2, 10 seconds left on p1
    {'Event': 'P1'},
    {'Event': 'IO'},
    {'Event': 'P1'},
    {'Event': 'IO'},
    {'Event': 'P1'},
    {'Event': 'IO'},

    
    #p2 arrives, 9 seconds b4 p3, 5 seconds left on p1, 0 seconds left on P2
    {'Event': 'P1'},
    {'Event': 'P2'},
    {'Event': 'P1'},
    {'Event': 'P2'},
    {'Event': 'P1'},
    {'Event': 'P2'},
    {'Event': 'P1'},
    {'Event': 'P2'},
    {'Event': 'P1'},

    #p3 arrives, 6 seconds b4 p4, 8 seconds left on p3, 2 seconds left on p1
    {'Event': 'P3'},
    {'Event': 'P1'},
    {'Event': 'P3'},
    {'Event': 'P1'},
    {'Event': 'P3'},
    {'Event': 'P1'},

    #p4 arrives, 3 seconds b4 p5, 1 second left on p1, 7 on p3, 8 on p4
    {'Event': 'P3'},
    {'Event': 'P1'},
    {'Event': 'P4'},

    #p5 arrives
    {'Event': 'P3'},
    {'Event': 'P1'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P3'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'P4'},
    {'Event': 'P5'},
    {'Event': 'IO'},
    {'Event': 'P5'},
    {'Event': 'IO'},
    {'Event': 'P5'},
    {'Event': 'IO'},
    {'Event': 'P5'},
    {'Event': 'IO'},
    {'Event': 'P5'},
    {'Event': 'IO'},
    {'Event': 'P5'},
]

divisions = [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58
]

Gantt.drawGantt(events,divisions,"Round Robin With IO")

